import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin,AiFillGithub} from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import { useState } from 'react'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false)

  return (
    <div  className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Ariyo Sulaimon Portfolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md: px20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
        <nav className='py-1 mb-12 flex justify-between '>
        <h1 className='text-xl font-burtons dark:text-white'>DevelopbyAriyo</h1>
          <ul className='flex  items-center'>
            <li>
              <BsFillMoonStarsFill className='cursor-pointer  text-2xl dark:text-white' onClick={()=> setDarkMode(!darkMode)}/>
              </li>
            <li><a href="#" className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Rusume</a></li>
          </ul>
        </nav>
        <div className='text-center p-10  py-10'>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'> Ariyo  Sulaimon</h2>
            <h3 className='text-2xl py-2  capitalize md:text-3xl dark:text-white'> Front end Developer</h3>
            <p className=' text-medium py-5 leading-7 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>Freelancer providing services for programming and design content
              needs. Join me down below and lets get cracking!</p>
        </div>
        <div className=' text-5xl flex justify-center gap-14 dark:text-white'>
          <AiFillGithub/>
          < AiFillLinkedin/>
          < AiFillTwitterCircle/>
        </div>
        <div className='relative mx-auto bg-gradient-to-b  from-teal-500  rounded-full w-80 h-80 mt-20 overflow-hidden md: h-96' >
            <Image src={deved} layout='fill' objectFit='cover'/>

        </div>
         
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 capitalize dark:text-white'> Service i offer</h3>
            <p className='text-md py-2 leading-8  text-gray-800 dark:text-white'>
              Since the beginning of my journey as a front end developer  Ive done remote work for 
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
              
              </p>
              <p className=' text-md py-3 leading-8 text-gray-800 dark:text-white'>
              I offer from a wide range of services, including brand design,
              programming and teaching.
              </p>
          </div>
          
          <div className='lg:flex gap-10 dark:text-white '>
          <div className=' text-center shadow-lg p-10 rounded-xl flex-1 '>
              <Image src={design} width={100} height={100} className='mx-auto'/>
              <h3 className='capitalize text-lg  font-medium pt-8 pb-2'>Skill on web development</h3>
              <p>

              </p>
              <p className='py 4 text-teal-600 capitalize dark:text-white'>HTML</p>
              <p className='text-gray-800 py-1 capitalize dark:text-white'>CSS</p>
              <p className='text-gray-800 py-1 capitalize dark:text-white '>TAILWIND</p>
              <p className='text-gray-800 py-1  capitalize dark:text-white'>JAVASCRIPT </p>
              <p className='text-gray-800 py-1 capitalize dark:text-white'>REACT.JS </p>
              <p className='text-gray-800 py-1  capitalize dark:text-white'>NEXT.JS </p>
              
            
            </div>
            <div className=' text-center shadow-lg p-10 rounded-xl flex-1'>
              <Image src={code} width={100} height={100} className='mx-auto'/>
              <h3 className='capitalize text-lg  font-medium pt-8 pb-2'>Skill on web development</h3>
              <p className="py-2">
                Do you have an idea for your next great website? Lets  code it out with
                
              </p>
              <p className='py 4 text-teal-600 capitalize dark:text-white'>HTML</p>
              <p className='text-gray-800 py-1 capitalize dark:text-white'>CSS</p>
              <p className='text-gray-800 py-1 capitalize dark:text-white'>TAILWIND</p>
              <p className='text-gray-800 py-1  capitalize dark:text-white'>JAVASCRIPT </p>
              <p className='text-gray-800 py-1 capitalize dark:text-white'>REACT.JS </p>
              <p className='text-gray-800 py-1  capitalize dark:text-white'>NEXT.JS </p>
              
            
            </div>
         
            <div className=' dark:text-white text-center shadow-lg p-10 rounded-xl flex-1 '>
              <Image src={consulting} width={100} height={100} className='mx-auto'/>
              <h3 className='capitalize text-lg  font-medium pt-8 pb-2'>Skill on web development</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <p className='py 4 text-teal-600 capitalize '>HTML</p>
              <p className='text-gray-800 py-1 capitalize dark:text-white '>CSS</p>
              <p className='text-gray-800 py-1 capitalize dark:text-white '>TAILWIND</p>
              <p className='text-gray-800 py-1  capitalize dark:text-white'>JAVASCRIPT </p>
              <p className='text-gray-800 py-1 capitalize dark:text-white'>REACT.JS </p>
              <p className='text-gray-800 py-1  capitalize dark:text-white'>NEXT.JS </p>
              
            
            </div>
          </div>
        </section>
        <section>
          <h3 className='text-3xl py-1 capitalize'>Portfolio</h3>
          <p className='text-md py-2 leading-8  text-gray-800 dark:text-white'>
              Since the beginning of my journey as a front end developer and
              developer, Ive done remote work for 
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
              
              </p>
              <p className=' text-md py-3 leading-8 text-gray-800'>
              I offer from a wide range of services, including brand design,
              programming and teaching.

              </p>
        </section>
      </main>
    </div>
  )
}